package com.medianote.app.ui.theme
import androidx.compose.ui.graphics.Color
val Purple80 = Color(0xFF7C4DFF)
val PurpleGrey80 = Color(0xFF7C4DFF)
val Pink80 = Color(0xFF7C4DFF)
val Purple40 = Color(0xFF7C4DFF)
val PurpleGrey40 = Color(0xFF7C4DFF)
val Pink40 = Color(0xFF7C4DFF)
val PrimaryPurple = Color(0xFF7C4DFF)
val PrimaryDark = Color(0xFF7C4DFF)
val SecondaryPurple = Color(0xFF7C4DFF)
val ControlHighlight = Color(0xFF7C4DFF)
val ControlNormal = Color(0xFF7C4DFF)
val BackgroundDark = Color(0xFF121212)
val SurfaceDark = Color(0xFF1E1E1E)
val BackgroundLight = Color(0xFFF5F5F5)
val SurfaceLight = Color(0xFFFFFFFF)
